from LightStrip import LightStrip
import time

print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('half red')
LightStrip.firstHalfRed()
time.sleep(2)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('half green')
LightStrip.firstHalfGreen()
time.sleep(2)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('clear')
LightStrip.clear()
time.sleep(1)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('all red')
LightStrip.allRed()
time.sleep(2)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('all green')
LightStrip.allGreen()
time.sleep(2)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('all blue')
LightStrip.allBlue()
time.sleep(2)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('clear')
LightStrip.clear()
time.sleep(1)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('second half red')
LightStrip.secondHalfRed()
time.sleep(2)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('second half green')
LightStrip.secondHalfGreen()
time.sleep(2)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('clear')
LightStrip.clear()
time.sleep(1)
print('~~~~~~~~~~~~~~~~~~~~~~~~~~')
